# Aktueller Screen 
Header header 
# Name des gerade sichtbaren Screens
string current_screen 
# z.B. "start", "raumwahl", "karte", "kaffeeautomat", "muelleimer", "bildungsangebote", "karten_ausgabe", "snackautomat", "spendenbox", "geschichte_hwr", "error1", "error2"   

# Language
Header header 
# Aktuelle Sprache
string language

# Stopp Button
Header header 
# Reset
string stop_druecken

# Start Button
Header header 
# Spracheingaben + POI Start
boolean start_druecken
